### ISSUE TITLE
编译提示 无法打开文件 "spdlogd.lib"

### ISSUE THREAD

**Issue by wolfrun001** [laomms/wxhelper#2]
使用 vs 2022 生成时 提示 LNK1104 无法打开文件"spdlogd.lib"

**Comment by laomms** [comment]
![2e588ec9-6b79-4a19-9e42-5960527c95c5](https://github.com/user-attachments/assets/73190965-79fd-4055-b029-b31cdd2915fb)
![b480a69f-7af7-43e5-b623-a2f4f1c03eba](https://github.com/user-attachments/assets/84a28ea4-0e61-4d44-96b1-ad8c7307965f)
