### ISSUE TITLE
Release版本无法注入，Debug版本可以成功，微信版本3.9.11.25

### ISSUE THREAD

**Issue by jeng8** [laomms/wxhelper#3]
Debug版本可以使用注入器注入，但换成Release版本注入不成功，也没有错误提示
netstat -ano | findstr 19088显示也为空
![image](https://github.com/user-attachments/assets/32c111a3-e6a8-4478-9817-a8abc3788121)

另外使用Visual Studio 2022进行调试时也不成功
![image](https://github.com/user-attachments/assets/633446df-d1d2-4457-ab30-df29e569ef52)
![image](https://github.com/user-attachments/assets/3164be89-cf06-4482-bed8-3920b4029cd2)
可以调出微信界面，然后弹窗下面黑窗
![image](https://github.com/user-attachments/assets/da3e0f0b-1a83-43d8-a5e0-8f0f3d3d1d7e)
Visual Studio 控制台输出如下
![image](https://github.com/user-attachments/assets/6dc544e8-121f-423e-bebf-ec6bd75892f2)
![image](https://github.com/user-attachments/assets/d1b79534-60fc-4b1f-ad2e-4f96a9ef93b0)

**Comment by laomms** [comment]
release是发行版本，不具有调试功能。
